<a href="https://colab.research.google.com/github/ichhitsapkota143/Machine-Learning/blob/main/Day5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Numpy***
Numpy is the fundamental package which provides a multidimensional array object

In [4]:
#import numpy
import numpy as np

In [2]:
#create a 1d array
#vector
arr1=np.array([1,2,3])
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
#2d array
#matrix
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
#3d array
#tensor
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [7]:
#we can make numpy array of required dimenssion

In [11]:
#datatype
#float data type array
arr=np.array([1,2,3],dtype=float)
print(arr)

[1. 2. 3.]


In [9]:
#boolean data type array
arra=np.array([1,2,3],dtype=bool)
print(arra)

[ True  True  True]


In [12]:
#complex data type array
arrb=np.array([1,2,3],dtype=complex)
print(arrb)

[1.+0.j 2.+0.j 3.+0.j]


In [13]:
#np.arange
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
np.arange(1,11,3)

array([ 1,  4,  7, 10])

In [15]:
#np.arange(start,end,diff)

In [22]:
#np.reshape
#to reshape given array into required shape
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [48]:
arr=np.arange(1,101,2)
twod_arr=arr.reshape(2,25)
print(arr)
print(twod_arr)
print(np.shape(twod_arr))

ValueError: cannot reshape array of size 500 into shape (2,25)

In [53]:
arr=np.linspace(-1000,1000,32)
arr_5=arr.reshape(2,2,2,2,2)
print(arr)

[-1000.          -935.48387097  -870.96774194  -806.4516129
  -741.93548387  -677.41935484  -612.90322581  -548.38709677
  -483.87096774  -419.35483871  -354.83870968  -290.32258065
  -225.80645161  -161.29032258   -96.77419355   -32.25806452
    32.25806452    96.77419355   161.29032258   225.80645161
   290.32258065   354.83870968   419.35483871   483.87096774
   548.38709677   612.90322581   677.41935484   741.93548387
   806.4516129    870.96774194   935.48387097  1000.        ]


In [35]:
#np.reshape(rows,column)

In [36]:
#np.reshape
#to reshape given array into required shape
np.arange(1,13).reshape(12,2)

ValueError: cannot reshape array of size 12 into shape (12,2)

In [37]:
#we cannot reshape the arr into a size < rows*column

In [39]:
#np.ones and np.zeros
#to create an array with either all ones or zeros
ones_arr=np.ones((2,5))
print(ones_arr)
print("\n \n \n")
zeros_arr=np.zeros((2,5))
print(zeros_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

 
 

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [41]:
#to generate a random number
np.random.random((2,5))

array([[0.90499116, 0.75979181, 0.47166257, 0.09746802, 0.90340314],
       [0.47497197, 0.51828772, 0.98874673, 0.18950787, 0.15306247]])

In [55]:
#np.linspace
#np.space(lower_range,upper_range,number_of_element)
np.linspace(-100,100,20,dtype=int)
#generates elements with equal distance

array([-100,  -90,  -79,  -69,  -58,  -48,  -37,  -27,  -16,   -6,    5,
         15,   26,   36,   47,   57,   68,   78,   89,  100])

In [47]:
#np.identity
#used to create an identity matrix
#np.identity(size_of_matrix)
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attrributes

In [5]:
a1=np.arange(10)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

np.ndim is used to find the dimenssion of the matrix
1d 2d or 3d and so on

In [57]:
np.ndim(a1)

1

In [58]:
np.ndim(a2)

2

In [59]:
np.ndim(a3)

3

In [61]:
a3.ndim #this can also be used

3

In [63]:
#shape
#used to determine the no of rows and column
a1.shape
#10 items in an array

(10,)

In [67]:
print(a2.shape)
#12 items with shape (3,4), four items in each row
print(a2)

(3, 4)
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [65]:
a3.shape

(2, 2, 2)

In [68]:
#size, number of items in an array
a1.size

10

In [69]:
a2.size

12

In [70]:
a3.size

8

In [71]:
#itemsize
a1.itemsize

8

8bit, int and floats are stored as 8bit

In [72]:
a2.itemsize

8

In [73]:
a3.itemsize

8

In [75]:
array1=np.arange(10,dtype=np.int32)
print(array1)
print(array1.itemsize)
print(array1.dtype)

[0 1 2 3 4 5 6 7 8 9]
4
int32


In [76]:
#here 4bit int is used

Changing Data type

In [6]:
#astype
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [9]:
a3.dtype

dtype('int64')

In [10]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [16]:
a1.astype(float)
print(a1)
print(a1.astype(float).dtype)

[0 1 2 3 4 5 6 7 8 9]
float64


# **Array Operation**

In [17]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [21]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [24]:
#scalar operation
#arithmatic
a1*2
#multiply each operation by 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [25]:
a1-1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [26]:
a1+1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
a1/12

array([[0.        , 0.08333333, 0.16666667, 0.25      ],
       [0.33333333, 0.41666667, 0.5       , 0.58333333],
       [0.66666667, 0.75      , 0.83333333, 0.91666667]])

In [28]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [30]:
#relational operator
a2>5
#compares each item with 5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [31]:
a1<3

array([[ True,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [32]:
#vector operation
#arithmetic
a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [33]:
a1*a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [34]:
a1-a2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [35]:
a1>a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [36]:
a1==a2

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [37]:
#in vector operation we perform the operations between elements of two array

In [38]:
a3=np.arange(10).reshape(2,5)

In [39]:
a3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
a1*a3

ValueError: operands could not be broadcast together with shapes (3,4) (2,5) 

In [41]:
a1-a3

ValueError: operands could not be broadcast together with shapes (3,4) (2,5) 

In [42]:
#We can see that we cannot perform operation between two arrays of different shape

In [48]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[26., 21., 97.],
       [ 5., 20., 15.],
       [ 3., 31., 38.]])

In [49]:
#min/max/sum/prod
np.max(a1)

np.float64(97.0)

In [52]:
np.min(a1)

np.float64(3.0)

In [53]:
np.sum(a1)
#sum of all elements

np.float64(256.0)

In [54]:
np.prod(a1)

np.float64(280751562000.0)

In [56]:
#max of each row
#0-> column and 1-> row
np.max(a1,axis=1)

array([97., 20., 38.])

In [57]:
#min of each column
np.min(a1,axis=0)

array([ 3., 20., 15.])

In [59]:
np.prod(a1,axis=0) #product of each element column wise

array([  390., 13020., 55290.])

In [60]:
#mean/median/std/var
np.mean(a1)

np.float64(28.444444444444443)

In [61]:
np.median(a1)

np.float64(21.0)

In [62]:
np.std(a1)

np.float64(26.474772524932366)

In [63]:
np.var(a1)

np.float64(700.9135802469137)

In [64]:
np.mean(a1,axis=1)

array([48.        , 13.33333333, 24.        ])

In [65]:
#trigonometric function
np.sin(a1)

array([[ 0.76255845,  0.83665564,  0.37960774],
       [-0.95892427,  0.91294525,  0.65028784],
       [ 0.14112001, -0.40403765,  0.29636858]])

In [66]:
np.cos(a1)

array([[ 0.64691932, -0.54772926, -0.92514754],
       [ 0.28366219,  0.40808206, -0.75968791],
       [-0.9899925 ,  0.91474236,  0.95507364]])

In [67]:
np.tan(a1)

array([[ 1.17875355, -1.52749853, -0.4103213 ],
       [-3.38051501,  2.23716094, -0.8559934 ],
       [-0.14254654, -0.44169557,  0.31030966]])

In [68]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)

In [69]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [72]:
#dot product can only if performed if (m*n)==(n*o)
#row of matrix 1 should be equal to column of matrix 2

In [73]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [74]:
np.dot(a3,a2)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

In [75]:
np.dot(a1,a2)

array([[ 860., 1004., 1148., 1292.],
       [ 200.,  240.,  280.,  320.],
       [ 428.,  500.,  572.,  644.]])

In [76]:
np.dot(a1,a3)

ValueError: shapes (3,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [77]:
#here error because it doesnt satisfy with the condition (3,3) and (4,3)

In [78]:
#log and exponents
np.log(a1)

array([[3.25809654, 3.04452244, 4.57471098],
       [1.60943791, 2.99573227, 2.7080502 ],
       [1.09861229, 3.4339872 , 3.63758616]])

In [80]:
np.exp(a1)

array([[1.95729609e+11, 1.31881573e+09, 1.33833472e+42],
       [1.48413159e+02, 4.85165195e+08, 3.26901737e+06],
       [2.00855369e+01, 2.90488497e+13, 3.18559318e+16]])

In [83]:
#round/floor/ceil
#round is used to round off to the nearest integer
np.random.random((2,3))*100

array([[85.21641195, 59.69412641, 92.18587131],
       [81.99184383, 84.47587837, 94.23588853]])

In [85]:
np.round(np.random.random((3,4)))

array([[0., 1., 0., 0.],
       [0., 1., 1., 0.],
       [1., 0., 0., 0.]])

In [89]:
np.round(a1)

array([[26., 21., 97.],
       [ 5., 20., 15.],
       [ 3., 31., 38.]])

In [90]:
np.floor(a1)
#used to round off to lower integer

array([[26., 21., 97.],
       [ 5., 20., 15.],
       [ 3., 31., 38.]])

In [93]:
np.ceil(a1)
#used to round off to upper integer

array([[26., 21., 97.],
       [ 5., 20., 15.],
       [ 3., 31., 38.]])

# **Indexing and Slicing**

In [94]:
a1=np.arange(10) #1d array
a2=np.arange(12).reshape(3,4) #2d array
a3=np.arange(8).reshape(2,2,2) #3d array

In [96]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
#indexing
a1[-1]

np.int64(9)

In [100]:
a1[0]

np.int64(0)

In [101]:
a1[4]

np.int64(4)

In [102]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
a2[1]

array([4, 5, 6, 7])

In [104]:
#if we need to find the element 6, first we need to find the index of row in which there is element 6, i.e 1

In [105]:
a2[1][2]

np.int64(6)

In [106]:
#then we find the index of that element 6 to find the element

In [108]:
#arr[row][column]

In [109]:
#to find element 2
a2[0][2]

np.int64(2)

In [110]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [111]:
#to find 5, we in which 2d array does that element exist, then we find the row of that element inside 2d then the column of the element

In [113]:
a3[1][0][1]

np.int64(5)

In [114]:
#second 2d array so [1]
#first row of 2d array so [0]
#second element so [1]

In [115]:
#to find 2
a3[0][1][0]

np.int64(2)

In [128]:
a2[0,:] #to print all elements of first row

array([0, 1, 2, 3])

In [129]:
a2[1,1:3] #to print second and third element of second row

array([5, 6])

# **Slicing**

In [116]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
a1[2:7] #to print 3 to 6

array([2, 3, 4, 5, 6])

In [119]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
a2[1:3] #select second and third row

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [132]:
a2[1:3,2:4] #to print second and third element of first and second row

array([[ 6,  7],
       [10, 11]])

In [134]:
a3[:1] #print only the first 2d array

array([[[0, 1],
        [2, 3]]])

In [137]:
a3[:1,1,1] #print 3

array([3])

In [138]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [139]:
#to find 5,6,7
a2[1,1:4]

array([5, 6, 7])

In [141]:
a3=np.arange(27).reshape(3,3,3)

In [142]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [155]:
#to print 16,17 and 19,20
a3[1:2,2:3,1:3] #to print 16,17

array([[[16, 17]]])

In [157]:
a3[2:3,0,1:3] #to print 19,20

array([[19, 20]])

Iteration in array

In [165]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [167]:
for i in a1:
  print( i)

0
1
2
3
4
5
6
7
8
9


In [159]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [164]:
for i in a2:
  print(i)
  print('Hello World')
  #prints every 1d array

[0 1 2 3]
Hello World
[4 5 6 7]
Hello World
[ 8  9 10 11]
Hello World


In [168]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [171]:
for i in a3:
  print(i)
  print('Hello World')
  #prints every 2d item

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Hello World
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
Hello World
[[18 19 20]
 [21 22 23]
 [24 25 26]]
Hello World


In [173]:
#to convert n-d array into 1d array and then iterate over them
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# **Reshape**

In [174]:
#reshape
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [176]:
a3.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [179]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [178]:
#transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [180]:
a2.T
#this can also be used

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [181]:
#ravel
#converts n-d array into 1d array
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [182]:
a3.shape

(3, 3, 3)

In [183]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])