<a href="https://colab.research.google.com/github/ichhitsapkota143/Machine-Learning/blob/main/Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sorting numpy array

In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,100,15)
a

array([51, 89, 81, 83, 79, 92, 26, 14, 77, 38, 51, 45, 55, 42, 89])

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[94, 82, 41, 62],
       [87, 53, 28, 39],
       [49, 89, 72, 75],
       [28, 46, 43, 17],
       [99, 49, 69,  8],
       [36, 18, 22, 21]])

In [5]:
#to sort
np.sort(a)

array([14, 26, 38, 42, 45, 51, 51, 55, 77, 79, 81, 83, 89, 89, 92])

In [7]:
#to sort row wise
np.sort(b)

array([[41, 62, 82, 94],
       [28, 39, 53, 87],
       [49, 72, 75, 89],
       [17, 28, 43, 46],
       [ 8, 49, 69, 99],
       [18, 21, 22, 36]])

In [8]:
#to sort column wise
np.sort(b,axis=0)

array([[28, 18, 22,  8],
       [36, 46, 28, 17],
       [49, 49, 41, 21],
       [87, 53, 43, 39],
       [94, 82, 69, 62],
       [99, 89, 72, 75]])

In [9]:
#to sort in descending order
np.sort(a)[::-1]

array([92, 89, 89, 83, 81, 79, 77, 55, 51, 51, 45, 42, 38, 26, 14])

In [15]:
#numpy append
#adds value to the end of the array
np.append(a,200)

array([ 51,  89,  81,  83,  79,  92,  26,  14,  77,  38,  51,  45,  55,
        42,  89, 200])

In [16]:
b

array([[94, 82, 41, 62],
       [87, 53, 28, 39],
       [49, 89, 72, 75],
       [28, 46, 43, 17],
       [99, 49, 69,  8],
       [36, 18, 22, 21]])

In [28]:
#to add column with all one's
np.append(b,np.ones((6,1)),axis=1)

array([[94., 82., 41., 62.,  1.],
       [87., 53., 28., 39.,  1.],
       [49., 89., 72., 75.,  1.],
       [28., 46., 43., 17.,  1.],
       [99., 49., 69.,  8.,  1.],
       [36., 18., 22., 21.,  1.]])

In [30]:
#to add a row with all zeros
np.append(b,np.zeros((1,4)),axis=0)

array([[94., 82., 41., 62.],
       [87., 53., 28., 39.],
       [49., 89., 72., 75.],
       [28., 46., 43., 17.],
       [99., 49., 69.,  8.],
       [36., 18., 22., 21.],
       [ 0.,  0.,  0.,  0.]])

In [31]:
#here if we dont write axis in above code, it converts the 2d array into 1d and then adds elements
np.append(b,np.zeros((1,4)))#,axis=0

array([94., 82., 41., 62., 87., 53., 28., 39., 49., 89., 72., 75., 28.,
       46., 43., 17., 99., 49., 69.,  8., 36., 18., 22., 21.,  0.,  0.,
        0.,  0.])

In [32]:
#concatenate
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [33]:
#to concatenate horizontially(row)
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [34]:
#to concatenate column wise
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
#simiar to vstack and hstack

In [38]:
#np.unique
#used to find unique values from the array
e=np.array([1,1,1,1,12,2,2,2,2,4,5,6,6,7,7])
print(e)
np.unique(e)

[ 1  1  1  1 12  2  2  2  2  4  5  6  6  7  7]


array([ 1,  2,  4,  5,  6,  7, 12])

In [43]:
#np.expand_dims
#used to expand the dimenssion of the array
#convert 1d array to 2d, 2d to 3d and so on
a.shape

(15,)

In [45]:
np.expand_dims(a,axis=1) #for row

array([[51],
       [89],
       [81],
       [83],
       [79],
       [92],
       [26],
       [14],
       [77],
       [38],
       [51],
       [45],
       [55],
       [42],
       [89]])

In [46]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [47]:
np.expand_dims(a,axis=0) #for column

array([[51, 89, 81, 83, 79, 92, 26, 14, 77, 38, 51, 45, 55, 42, 89]])

In [49]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [50]:
#np.where
#used to find the index of the array where the given condition is satisfied
np.where(a>50)

(array([ 0,  1,  2,  3,  4,  5,  8, 10, 12, 14]),)

In [51]:
np.where(a<50)

(array([ 6,  7,  9, 11, 13]),)

In [52]:
np.where(a==50)

(array([], dtype=int64),)

In [53]:
np.where(a%2==0)

(array([ 5,  6,  7,  9, 13]),)

In [55]:
#replace all values >50 with 0
a[np.where(a>50)]=0
print(a)

[ 0  0  0  0  0  0 26 14  0 38  0 45  0 42  0]


In [56]:
#alternatively
np.where(a>50,0,a)
#np.where(condition,whatIfTrue,whatIfFalse)

array([ 0,  0,  0,  0,  0,  0, 26, 14,  0, 38,  0, 45,  0, 42,  0])

In [57]:
#to replace all 0's with 6
np.where(a==0,6,a)

array([ 6,  6,  6,  6,  6,  6, 26, 14,  6, 38,  6, 45,  6, 42,  6])

In [59]:
#np.argmax
#returns indices of the max element of the array in a particular axis
a=np.random.randint(1,100,15)
a

array([43, 28, 94, 96, 78, 82, 29, 16, 16, 54, 96, 45, 28, 50, 81])

In [60]:
np.argmax(a)

np.int64(3)

In [61]:
b

array([[94, 82, 41, 62],
       [87, 53, 28, 39],
       [49, 89, 72, 75],
       [28, 46, 43, 17],
       [99, 49, 69,  8],
       [36, 18, 22, 21]])

In [65]:
np.argmax(b,axis=1) #return index of each maximum element of the row

array([0, 0, 1, 1, 0, 0])

In [66]:
np.argmax(b,axis=0)#return index of each maximum element of the column

array([4, 2, 2, 2])

In [67]:
#np.argmin
#gives minimum value
np.argmin(a)

np.int64(7)

In [68]:
np.argmin(b,axis=0)

array([3, 5, 5, 4])

In [69]:
np.argmin(b,axis=1)

array([2, 2, 0, 3, 3, 1])

In [70]:
#np.cumsum
#used to compute the  cumulative sum of array elements over a given axis
a

array([43, 28, 94, 96, 78, 82, 29, 16, 16, 54, 96, 45, 28, 50, 81])

In [71]:
np.cumsum(a)

array([ 43,  71, 165, 261, 339, 421, 450, 466, 482, 536, 632, 677, 705,
       755, 836])

In [73]:
b

array([[94, 82, 41, 62],
       [87, 53, 28, 39],
       [49, 89, 72, 75],
       [28, 46, 43, 17],
       [99, 49, 69,  8],
       [36, 18, 22, 21]])

In [72]:
np.cumsum(b) #converts into 1d and then performs cumulative sum

array([  94,  176,  217,  279,  366,  419,  447,  486,  535,  624,  696,
        771,  799,  845,  888,  905, 1004, 1053, 1122, 1130, 1166, 1184,
       1206, 1227])

In [74]:
np.cumsum(b,axis=0) #column wise

array([[ 94,  82,  41,  62],
       [181, 135,  69, 101],
       [230, 224, 141, 176],
       [258, 270, 184, 193],
       [357, 319, 253, 201],
       [393, 337, 275, 222]])

In [75]:
np.cumsum(b,axis=1)#row wise

array([[ 94, 176, 217, 279],
       [ 87, 140, 168, 207],
       [ 49, 138, 210, 285],
       [ 28,  74, 117, 134],
       [ 99, 148, 217, 225],
       [ 36,  54,  76,  97]])

In [76]:
#np.cumprod
#finds the cumulative product
np.cumprod(a)

array([                  43,                 1204,               113176,
                   10864896,            847461888,          69491874816,
              2015264369664,       32244229914624,      515907678633984,
          27859014646235136,  2674465406038573056, -8776265244231073792,
       -5927753880245895168, -1239788832941932544, -8189175099748777984])

In [77]:
np.cumprod(b,axis=0)

array([[         94,          82,          41,          62],
       [       8178,        4346,        1148,        2418],
       [     400722,      386794,       82656,      181350],
       [   11220216,    17792524,     3554208,     3082950],
       [ 1110801384,   871833676,   245240352,    24663600],
       [39988849824, 15693006168,  5395287744,   517935600]])

In [78]:
#np.percentile
#used to compute the nth percentile of the given data(array)
a

array([43, 28, 94, 96, 78, 82, 29, 16, 16, 54, 96, 45, 28, 50, 81])

In [79]:
np.percentile(a,100) #maximum

np.float64(96.0)

In [80]:
np.percentile(a,50) #median

np.float64(50.0)

In [83]:
np.median(a)

np.float64(50.0)

In [81]:
np.percentile(a,0) #minimum

np.float64(16.0)

np.float64(50.0)

In [89]:
#np.histogram
#gives frequency count of given number
#bins means upper bound of the class
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 2, 3, 0, 2, 2, 0, 1, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [88]:
#the upper array gives the frequency of the class

In [91]:
#np.corrcoef
#gives correlation coefficient, pearson product
salary=np.array([10000,20000,30000,40000])
experience=np.array([1,3,5,2])
np.corrcoef(salary,experience)


array([[1.        , 0.37796447],
       [0.37796447, 1.        ]])

In [92]:
#the upper row gives salary and experience correlation in both ways, salary-salary, salary-experience,experience-salary,experience-experience

In [93]:
#np.isin
#checks multiples items in an array, to search n numbers of elements in the array
items=np.array([10,20,30,40,50,60,70,80,90,100])
np.isin(items,[5,10,15,20])

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [95]:
items[np.isin(items,[5,10,15,20])]

array([10, 20])

In [97]:
#np.flip
#reverses the order of the array element along the specified axis, preserving the shape of the array
print(a)
np.flip(a)

[43 28 94 96 78 82 29 16 16 54 96 45 28 50 81]


array([81, 50, 28, 45, 96, 54, 16, 16, 29, 82, 78, 96, 94, 28, 43])

In [98]:
#gives mirror image

In [99]:
b

array([[94, 82, 41, 62],
       [87, 53, 28, 39],
       [49, 89, 72, 75],
       [28, 46, 43, 17],
       [99, 49, 69,  8],
       [36, 18, 22, 21]])

In [100]:
np.flip(b)

array([[21, 22, 18, 36],
       [ 8, 69, 49, 99],
       [17, 43, 46, 28],
       [75, 72, 89, 49],
       [39, 28, 53, 87],
       [62, 41, 82, 94]])

In [101]:
#flips both rows and column at the same time if axis is not mentioned

In [102]:
np.flip(b,axis=0) #column wise flip

array([[36, 18, 22, 21],
       [99, 49, 69,  8],
       [28, 46, 43, 17],
       [49, 89, 72, 75],
       [87, 53, 28, 39],
       [94, 82, 41, 62]])

In [103]:
np.flip(b,axis=1)# row wise flip

array([[62, 41, 82, 94],
       [39, 28, 53, 87],
       [75, 72, 89, 49],
       [17, 43, 46, 28],
       [ 8, 69, 49, 99],
       [21, 22, 18, 36]])

In [104]:
#np.put
#replaces specific elements of array with given value
a

array([43, 28, 94, 96, 78, 82, 29, 16, 16, 54, 96, 45, 28, 50, 81])

In [108]:
#change 43 to 110 and 28 to 530
np.put(a,[0,1],[110,530]) #permanent change
#np.put(array,listofIndex,replacevalue)
print(a)

[110 530  94  96  78  82  29  16  16  54  96  45  28  50  81]


In [110]:
#np.delete
#returns a new array with the specified elements removed from the input array using index
np.delete(a,0) #delete the 0th element

array([530,  94,  96,  78,  82,  29,  16,  16,  54,  96,  45,  28,  50,
        81])

In [111]:
np.delete(a,[0,2,4,6])

array([530,  96,  82,  16,  16,  54,  96,  45,  28,  50,  81])

# **Set Function**

In [112]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

In [113]:
#np.union1d
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [114]:
#intersect
np.intersect1d(m,n)

array([3, 4, 5])

In [116]:
#setdifference
np.setdiff1d(m,n)

array([1, 2])

In [117]:
np.setdiff1d(n,m)

array([6, 7])

In [119]:
#np.in1d
np.in1d(m,1)

<ipython-input-119-2e6c9e764af1>:2: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,1)


array([ True, False, False, False, False])

In [121]:
#xor
#remove common and return rest
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [122]:
#np.clip
#used to clip/limit the values in array
a

array([110, 530,  94,  96,  78,  82,  29,  16,  16,  54,  96,  45,  28,
        50,  81])

In [123]:
#to clip values between 25,75
np.clip(a,25,75)
#np.clip(array,minValue,maxValue)

array([75, 75, 75, 75, 75, 75, 29, 25, 25, 54, 75, 45, 28, 50, 75])

In [124]:
#here any value greater than 75 is replaced by 75 and less than 25 is replaced by 25

# **Pandas**
Pandas is a fast,powerful, felxible and easy to use open source data analysis and manipulation tool

In [125]:
import pandas as pd

# Series from list

In [126]:
#string
country=['Nepal','India','USA','China','Japan']
country

['Nepal', 'India', 'USA', 'China', 'Japan']

In [127]:
pd.Series(country)

0    Nepal
1    India
2      USA
3    China
4    Japan
dtype: object

In [128]:
#integer series
runs=[13,24,56,78,100]
pd.Series(runs)

0     13
1     24
2     56
3     78
4    100
dtype: int64

In [129]:
#custom index
marks=[67,57,89,100]
subjects=['Maths','Science','English','Nepali']
pd.Series(marks,index=subjects)

Maths       67
Science     57
English     89
Nepali     100
dtype: int64

In [132]:
#setting a name
marks=pd.Series(marks,index=subjects,name="Ichhit's Mark")
marks

Maths       67
Science     57
English     89
Nepali     100
Name: Ichhit's Mark, dtype: int64

# Series from dictionary

In [135]:
marks={
    'maths':67,
    'english':57,
    'science':89,
    'computer':100
}
marks_series=pd.Series(marks,name="Ichhit's Marks")
marks_series

maths        67
english      57
science      89
computer    100
Name: Ichhit's Marks, dtype: int64

# Series attributes

In [138]:
#size
#gives the number of items in the series
marks_series

maths        67
english      57
science      89
computer    100
Name: Ichhit's Marks, dtype: int64

In [137]:
#size
marks_series.size

4

In [139]:
#dtype
marks_series.dtype

dtype('int64')

In [140]:
#name
marks_series.name

"Ichhit's Marks"

In [141]:
#is_unique
marks_series.is_unique

True

In [144]:
pd.Series([1,1,2,3,4]).is_unique

False

In [145]:
#index
marks_series.index

Index(['maths', 'english', 'science', 'computer'], dtype='object')

In [147]:
pd.Series([1,2,3,4,5]).index

RangeIndex(start=0, stop=5, step=1)

In [146]:
#values
marks_series.values

array([ 67,  57,  89, 100])

# **Series using read_csv**

In [166]:
#with one col
subs=pd.read_csv('subs.csv')
subs

Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [152]:
type(pd.read_csv('subs.csv'))

pandas.core.frame.DataFrame

In [192]:
#with 2 cols.
vk=pd.read_csv('kohli_ipl.csv',index_col='match_no')
vk

runs
match_no      
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [164]:
movies=pd.read_csv('bollywood.csv',index_col='movie')
movies

lead
movie                                                 
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [170]:
#head and tail
subs.head()
#gives first five data

Subscribers gained
0                  48
1                  57
2                  40
3                  43
4                  44

In [169]:
subs.tail()
#gives last five data

Subscribers gained
360                 231
361                 226
362                 155
363                 144
364                 172

In [171]:
vk.head(3)

runs
match_no      
1            1
2           23
3           13

In [173]:
vk.head(10)

runs
match_no      
1            1
2           23
3           13
4           12
5            1
6            9
7           34
8            0
9           21
10           3

In [174]:
vk.tail(7)

runs
match_no      
209         58
210         30
211          0
212         20
213         73
214         25
215          7

In [176]:
#sample
#gives one movie randomly
movies.sample()

lead
movie                          
Heroes (2008 film)  Sohail Khan

In [177]:
movies.sample(10)

lead
movie                                     
Ek Main Aur Ekk Tu          Kareena Kapoor
Student of the Year             Alia Bhatt
A Decent Arrangement          Shabana Azmi
Love Story 2050              Harman Baweja
Love U...Mr. Kalakaar!      Tusshar Kapoor
Alag                         Akshay Kapoor
OMG – Oh My God!              Paresh Rawal
Commando: A One Man Army    Vidyut Jammwal
Filmistaan                   Sharib Hashmi
Dharam Sankat Mein        Naseeruddin Shah

In [178]:
#value_count
#used to count the number of repetation of values in descending order
movies.value_counts()

lead            
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Naveen Bawa          1
Naushaad Abbas       1
Nauheed Cyrusi       1
Natalia Janoszek     1
Nishikant Kamat      1
Name: count, Length: 566, dtype: int64

In [182]:
#sort_value
#sorted in ascending order
#eg: to find the runs scored in each match in by vk
vk.sort_values('runs')

runs
match_no      
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [183]:
#for descending order
vk.sort_values('runs',ascending=False)

runs
match_no      
128        113
126        109
123        108
120        100
164        100
...        ...
93           0
130          0
206          0
207          0
211          0

[215 rows x 1 columns]

In [186]:
#to find highest run scored by vk
vk.sort_values('runs',ascending=False).head(1)

runs
match_no      
128        113

In [191]:
#sort_index
#elements are sorted as per values
vk

runs
match_no      
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]

In [189]:
vk.sort_values('runs',inplace=True)

In [190]:
vk

runs
match_no      
8            0
87           0
93           0
91           0
206          0
...        ...
164        100
120        100
123        108
126        109
128        113

[215 rows x 1 columns]